export interface IAddress {
    id: string,
    propertyId: string,
    type: string,
    subtype: string,
    utility: string,
    cep: number,
    state: string,
    city: string,
    street: string,
    publicPlace: boolean,
    number: number,
    unity: number,
    towerBlock: string,
    nameTowerBlock: string,
    floor: string,
    block: string,
    batch: string,
    kilometer: number,
    district: string,
    marketRegion: string,
    bathrooms: number,
    rooms: number,
    kitchens: number,
    garageSpots: number,
    area: number
}